version: '3'
services:
    mysql:
        container_name: messenger-mysql
        build: ./mysql
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=hnthsy6=
        ports:
          - "3307:3306"
        volumes:
          - "./data/mysql:/var/lib/mysql"

    couchdb:
        container_name: messenger-couchdb
        build: ./couchdb
        environment:
          - COUCHDB_USER=root
          - COUCHDB_PASSWORD=hnthsy6=
        ports:
          - "5985:5984"
        volumes:
          - "./data/couchdb:/usr/local/var/lib/couchdb"

    back:
        container_name: messenger-back
        build: ./back
        ports:
          - "8080:8080"
        depends_on:
          - mysql
          - couchdb
        volumes:
          - "./logs/messenger:/var/log/messenger"